application: csgamifyme
version: 1
runtime: python27

api_version: 1


threadsafe: true
handlers:
- url: /clothes-pics
  static_dir: clothes-pics 

- url: /images
  static_dir: images

- url: .*
  script: main.application
  login: required

libraries:
- name: jinja2
  version: "latest"
- name: webapp2
  version: "latest"
